[profile.default]
test-threads = "num-cpus"
fail-fast = false
slow-timeout = { period = "5s", terminate-after = 3 }
status-level = "fail"
final-status-level = "fail"
failure-output = "immediate-final"

[profile.ci]
fail-fast = true
retries = 1
status-level = "fail"
final-status-level = "fail"
